-- ---------------------------------------------------------------------------
-- Story 9-3: Immutable Audit Log (audit_events)
-- LGPD & Compliance — Epic 9
--
-- Design decisions embedded here:
--   dec-015 (SEC-005): id generated by app via generateId() (UUIDv7), no DB default
--   dec-018 (SEC-006): ip_address TEXT (not INET) — supports IPv6 bracket notation,
--                       proxies and 'unknown' values without DB rejection
--   dec-016 (SEC-011): user_id nullable — public route captures may have no auth user
--   dec-019 (SEC-007): payload JSONB truncated by app layer if > 65536 bytes
--   dec-024 (REQ-014): indexes on (tenant_id, timestamp DESC), (tenant_id, user_id),
--                       (tenant_id, action) for efficient filtering
--   FR-INFRA-02 / SEC-001 / SEC-002: ONLY INSERT + SELECT policies.
--                       NO UPDATE. NO DELETE. Immutability enforced by policy absence.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- 1. Create audit_events table
-- ---------------------------------------------------------------------------

CREATE TABLE "audit_events" (
    -- id: UUIDv7 generated by app via generateId() — NOT a DB-generated default
    "id"             UUID         NOT NULL,
    -- tenant_id: NEVER passed as function param; injected via AsyncLocalStorage
    "tenant_id"      UUID         NOT NULL,
    -- user_id: nullable — captures on @Public() routes may have no authenticated user
    "user_id"        UUID,
    -- action: closed enum enforced at both app layer (Zod) and DB (CHECK)
    "action"         TEXT         NOT NULL CHECK (action IN (
                         'create', 'update', 'delete',
                         'login', 'logout', 'auth_failure',
                         'config_change', 'export'
                     )),
    -- resource: domain entity or path segment (e.g. 'user', 'group', 'trail')
    "resource"       TEXT         NOT NULL,
    -- resource_id: nullable for bulk or collection-level operations
    "resource_id"    TEXT,
    -- ip_address: TEXT (not INET) — supports IPv6 bracket notation and proxies
    -- dec-018 (SEC-006): TEXT chosen for compatibility with all proxy/header formats
    "ip_address"     TEXT         NOT NULL,
    "user_agent"     TEXT         NOT NULL,
    -- previous_state: JSONB — null when AuditContext not populated by service
    --   dec-016 (SEC-011): only filled when service explicitly sets it via AuditContext
    "previous_state" JSONB,
    -- new_state: JSONB — may be truncated if > AUDIT_PAYLOAD_TRUNCATE_BYTES (65536)
    --   dec-019 (SEC-007): app layer replaces oversized payloads with truncation marker
    "new_state"      JSONB,
    -- timestamp: when the action occurred; defaults to DB now() as safety net
    "timestamp"      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    -- severity: info | warning | critical — derived by audit.severity.ts from action+resource
    "severity"       TEXT         NOT NULL CHECK (severity IN ('info', 'warning', 'critical')),

    CONSTRAINT "audit_events_pkey" PRIMARY KEY ("id")
);

-- ---------------------------------------------------------------------------
-- 2. Foreign key: tenant cascade (consistent with project FK conventions)
-- ---------------------------------------------------------------------------

ALTER TABLE "audit_events"
    ADD CONSTRAINT "audit_events_tenant_id_fkey"
    FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE;

-- ---------------------------------------------------------------------------
-- 3. Indexes (dec-024, REQ-014)
-- ---------------------------------------------------------------------------

-- Primary query: list events ordered by time for a tenant (most common access pattern)
CREATE INDEX "idx_audit_events_tenant_timestamp"
    ON "audit_events" ("tenant_id", "timestamp" DESC);

-- Filter by member: used in listEvents?userId= query parameter
CREATE INDEX "idx_audit_events_tenant_user"
    ON "audit_events" ("tenant_id", "user_id");

-- Filter by action type: used in listEvents?action= query parameter
CREATE INDEX "idx_audit_events_tenant_action"
    ON "audit_events" ("tenant_id", "action");

-- ---------------------------------------------------------------------------
-- 4. RLS — Row Level Security (append-only: INSERT + SELECT only)
--
-- SECURITY NOTE: There are intentionally NO UPDATE or DELETE policies.
-- Any attempt to UPDATE or DELETE rows will be rejected by PostgreSQL
-- because no permissive policy exists for those operations.
-- This enforces audit log immutability at the database level.
-- FR-INFRA-02, SEC-001, SEC-002.
-- ---------------------------------------------------------------------------

ALTER TABLE "audit_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "audit_events" FORCE ROW LEVEL SECURITY;

-- INSERT: tenant-scoped writes (app role sets app.current_tenant_id via withTenantTx)
CREATE POLICY "audit_events_tenant_insert" ON "audit_events"
    FOR INSERT
    WITH CHECK (
        tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid
    );

-- SELECT: tenant-scoped reads (same mechanism)
CREATE POLICY "audit_events_tenant_select" ON "audit_events"
    FOR SELECT
    USING (
        tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid
    );

-- SUPER ADMIN reads cross-tenant via prisma.client (bypass RLS, non-transactional connection)
-- No additional policy needed: super-admin uses PrismaService.client which does NOT set
-- app.current_tenant_id, and bypasses RLS because metanoia_admin role has BYPASSRLS.
-- dec-015 (SEC-005): confirmed pattern from super-admin-tenants.repository.ts.
